// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9lbVutqR0dGLvXrwDyxkQwLMDCc34pQ',
    appId: '1:630387150504:web:e232466bd9a719d221fc9d',
    messagingSenderId: '630387150504',
    projectId: 'myshetribe',
    authDomain: 'myshetribe.firebaseapp.com',
    storageBucket: 'myshetribe.firebasestorage.app',
    measurementId: 'G-WX6XWEDR97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdY59Gxi21PkwsmboOgu8UruVXbtlmiUU',
    appId: '1:630387150504:android:cfc70cb2b6416a0821fc9d',
    messagingSenderId: '630387150504',
    projectId: 'myshetribe',
    storageBucket: 'myshetribe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq8X3kTj5IpWksV2tGEKinapbxN_OCkUw',
    appId: '1:630387150504:ios:8631f60f9a9152af21fc9d',
    messagingSenderId: '630387150504',
    projectId: 'myshetribe',
    storageBucket: 'myshetribe.firebasestorage.app',
    iosBundleId: 'com.app.myshetribe',
  );
}
